---
- name: LSO deployer
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
# Add pre-deploy checks to ensure the installation will be a success  
# vvvv Below ansible can be a playbook block vvvv
  - name: create project for LSO
    kubernetes.core.k8s:
      name: openshift-local-storage
      state: present
      api_version: v1
      kind: Namespace
##
#  Get nodes by label "node-role.kubernetes.io/worker" to deploy LSO
##
  - name: Using vars while using label_selectors
    kubernetes.core.k8s_info:
      kind: Node
      label_selectors:
        - node-role.kubernetes.io/worker 
    register: workerNodes

##
# Applies label cluster.ocs.openshift.io/openshift-storage: "" to deploy ODF
##

  - name: Patching nodes with correct label for ODF/OCS
    kubernetes.core.k8s:
      state: patched
      kind: Node
      name: "{{ item.name }}"
      definition: 
        metadata:
          labels:
            cluster.ocs.openshift.io/openshift-storage: ""
    loop: 
    - "{{ workerNodes['resources'][0]['metadata'] }} "
    - "{{ workerNodes['resources'][1]['metadata'] }} "
    - "{{ workerNodes['resources'][2]['metadata'] }} "

  - name: create operator configs for LSO
    kubernetes.core.k8s:
      src: ./operator.yaml
      state: present
      namespace: openshift-local-storage
##
# vvv Add below a check that wait on the local-storage-operator pod to be running vvv
# The below ansible thingy can make the playbook wait based on pod/deployment conditions
# Could be the thing that makes the trick
##
  - name: Waiting for the operator pod to start up
    kubernetes.core.k8s_info:
      kind: Pod
      wait: yes
      namespace: openshift-local-storage
      wait_sleep: 10
      wait_timeout: 360
  # There are several methods to feed volume creation to the operator
  # Decide which ones to use for each use case.(Selector or something)
  - name: create operator configs for LSO
    kubernetes.core.k8s:
      state: present
      namespace: openshift-local-storage
      src: ./localVolumeSet.yml

  - name: Waiting for the diskmaker pods to get up and running to finish successfully
    kubernetes.core.k8s_info:
      kind: Pod
      wait: yes
      namespace: openshift-local-storage
      wait_sleep: 10
      wait_timeout: 360

