---
- name: LSO deployer
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
# Add pre-deploy checks to ensure the installation will be a success  
# vvvv Below ansible can be a playbook block vvvv
  - name: create project for LSO
    kubernetes.core.k8s:
      name: openshift-local-storage
      state: present
      api_version: v1
      kind: Namespace
##
#  Get nodes by label "node-role.kubernetes.io/worker" to deploy LSO
##
  - name: Using vars while using label_selectors
    kubernetes.core.k8s_info:
      kind: Node
      label_selectors:
        - node-role.kubernetes.io/worker 
    register: workerNodes

##
# Applies label cluster.ocs.openshift.io/openshift-storage: "" to deploy ODF
##

  - name: Patching nodes with correct label for ODF/OCS
    kubernetes.core.k8s:
      state: patched
      kind: Node
      name: "{{ item.name }}"
      definition: 
        metadata:
          labels:
            cluster.ocs.openshift.io/openshift-storage: ""
    loop: 
    - "{{ workerNodes['resources'][0]['metadata'] }} "
    - "{{ workerNodes['resources'][1]['metadata'] }} "
    - "{{ workerNodes['resources'][2]['metadata']  }} "

  - name: create operator configs for LSO
    kubernetes.core.k8s:
      src: ./operator.yaml
      state: present
      namespace: openshift-local-storage
##
# ^^^ the above task is very fast and can crash the rest of the playbook ^^^
# vvv Add below a check that wait on the local-storage-operator pod to be running vvv
##

  # There are several methods to feed volume creation to the operator
  # Decide which ones to use for each use case.(Selector or something)
  - name: create operator configs for LSO
    kubernetes.core.k8s:
      state: present
      namespace: openshift-local-storage
      src: ./localVolumeSet.yml
# -> It takes around two minutes once the pods are deployed to provision the new PVs
# -> Add a sleeper
# -> Add a check at the end to ensure that it deployed successfully
